application: app-id
version: dev
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*\.git/.*)
- ^(.*/)?.*\.bat

default_expiration: "2d"

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon

- url: /_ah/mail/post@.*
  script: main.app
  login: admin

- url: /admin.*
  script: admin.app
  login: admin

- url: /*
  script: main.app

- url: /bm/.*
  script: main.app

- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- deferred: on
- remote_api: off
- appstats: on

inbound_services:
- mail