application: app-id
module: default
version: master
runtime: python27
api_version: 1
threadsafe: false
default_expiration: 7d

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*\.git/.*)
- ^(.*/)?.*\.bat

handlers:

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon

- url: /_ah/login_required
  script: app.admin.app

- url: /_ah/mail/.+
  script: app.admin.app
  login: admin

- url: /admin.*
  script: app.admin.app
  login: admin

- url: /*
  script: app.main.app

- url: /bm/.*
  script: app.main.app

- url: /twitter.*
  script: app.twitter.app

- url: /.*
  script: app.main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: markupsafe
  version: latest
- name: ssl
  version: latest

builtins:
- deferred: on
- remote_api: off
- appstats: on
- admin_redirect: on

inbound_services:
- mail
