application: app-id
version: dev
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*\.git/.*)
- ^(.*/)?.*\.bat

default_expiration: "2d"

handlers:

- url: /*.manifest.appcache
  static_files: static/manifest.appcache
  upload: static/manifest.appcache
  mime_type: text/cache-manifest

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon

- url: /_ah/mail/post@.*
  script: app.main.app

- url: /admin.*
  script: app.admin.app
  login: admin

- url: /*
  script: app.main.app

- url: /bm/.*
  script: app.main.app

- url: /twitter.*
  script: app.twitter.app

- url: /.*
  script: app.main.app
  login: required

- url: /mapreduce(/.*)?
  script: mapreduce.reduce.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: markupsafe
  version: latest

builtins:
- deferred: on
- remote_api: off
- appstats: off

inbound_services:
- mail

includes:
- mapreduce/include.yaml